:source-highlighter: highlight.js

= Exercise 1.0 - Installing Ansible Core and Ad-hoc commands

== Installing Ansible Core

Before we can use ansible to run some stuff, we've got to get Ansible installed.
Follow these few, simple steps and you should be good to go.  If you have trouble, let
one of your instructors know and we'll get you sorted.

====

Step 1: Login to your control node
[source,bash]
----
ssh <username>@<IP of your control node>
----
Step 2: Install Ansible Core
[source,bash]
----
sudo yum install -y ansible
----

====

== Running Ad-hoc commands
Now that you've got ansible installed, we are going to run some ad-hoc commands to help you get a feel for how Ansible works.


====
Step 1: Take a look at your web node's configuration.  The ```setup``` module displays ansible facts about an endpoint.
[source,bash]
----
ansible web -m setup
----
Step 2: Now, let's install Apache using the ```yum``` module
[source,bash]
----
ansible web -m yum -a "name=httpd state=present" -b
----
Step 3: OK, Apache is installed now so let's start it up using the ```service``` module
[source,bash]
----
ansible web -m service -a "name=httpd state=started" -b
----
Step 4: Finally, let's clean up after ourselves.  First, stop the httpd service
[source,bash]
----
ansible web -m service -a "name=httpd state=stopped" -b
----
Step 5: Second, remove the Apache package
[source,bash]
----
ansible web -m yum -a "name=httpd state=absent" -b
----
====
