:badges:
:icons:
:iconsdir: http://people.redhat.com/~jduncan/images/icons
:imagesdir: http://tower.workshop.bos.redhatgov.io/_images
:date: 19-Jan-2017
:location: Boston, MA
:tower_url: https://ansible-tower-bos.redhatgov.io
:source-highlighter: highlight.js
:source-language: yaml

= Automation for Everyone

---

.Today's Agenda
****
* Arrivals / Breakfast - 8:15 - 8:45
* Introductions / Agenda - 8:45 - 9:00
* Presentation - 9:00 - 9:30
* Setup - 9:30 - 9:40
* Exercise 1.0 - Ad-Hoc Commands - 9:40 - 10:00
* Break - 10:00 - 10:10
* Exercise 1.1 - Writing Your First Playbook - 10:10 - 10:40
* Exercise 1.2 - Running Your First Playbook - 10:40 - 11:00
* Exercise 1.3 - Installing Ansible Tower - 11:00 - 11:30
* Exercise 1.4 - Configuring Ansible Tower - 11:30 - 12:00
* Lunch - 12:00 - 12:30
* Exercise 1.5 - Creating and Running a Job Template - 12:30 - 1:00
* Resources, Wrap Up - 1:00 - 1:30
****

.Before We Get Started
****
[.lead]
Overview

Today is meant for anyone who has any exposure to Ansible, whether you have used it or not. We are going to start with a short overview (yes, slideware) and then we'll get into the lab as soon as possible. That is where we will spend most of our time.

[.lead]
Your Responsibilities

* Have a discussion. This will be boring if it's just us up here talking for over 4 hours.
* Participate. We are going to cut you loose with Ansible here in just a little while. Have questions. Have opinions.

Hopefully you have your laptop with you. If not, please find a shoulder-surfing buddy. See? Not only can we dig into Ansible but you can make a new friend!

[.lead]
Conventions Used in This Document
[TIP]
.Whenever you see a section like this, please pay close attention.  We are leading you through a process.
====

====

====
Step 1: Run this command to do something or other
[source,bash]
----
ansible web -m setup
----
* Step 2: Edit this file in this specific way

[source,bash]
----
---
 - hosts: web
   name: This is a play within a playbook
   become: yes
   vars:
     httpd_packages:
       - httpd
       - mod_wsgi
----
[IMPORTANT]
Do not cut and paste text from this document.  We really want you to learn ansible during this workshop,
and part of that experience is typing out YAML and understanding it's syntax, spacing, and alignments.
====


[.lead]
Location-Specific Information
[IMPORTANT]
.WiFi Access
====
ssid: `TBD`
====
****

.Today's Team
****
[.lead]
Pete Bowden - Solutions Architect

Pete is a Solutions Architect with Red Hat working with enterprise clients in the Northeast. Prior to life at Red Hat, he was a software and dev-ops engineer,
focusing on micro-services and automated deployments. He currently lives in West Hartford, CT with a dog and a cat that adopted him.
In his spare time he can be found hiking or attempting to perfect a home-brew clone of a New England IPA.

[.lead]
Gerald Dykeman - Domain Architect - Ansible

Gerald joined Red Hat in August 2016 as a Domain Architect.  His focus is on all things Ansible Core and Tower as well
as specializing in Ansible's network automation capabilities.
Gerald has a networking background, previously working with a range of solutions from Small Business to
Service Provider.  In the last couple years before joining Red Hat, he focused on using Ansible to automate OpenStack solutions.

[.lead]
Bill Hirsch - Solutions Architect

Bill is a Solutions Architect with Red Hat focused on Northeast public sector accounts.  As an account SA, he is responsible for all Red Hat offerings,
but has a passion for Ansible.  He has a background in Linux/Unix systems administration, management, and prior to joining Red Hat served as a Director
of Infrastructure at the University of Pittsburgh Medical Center.
Bill lives in Pittsburgh with his wife, 3 boys, and ever-shedding pets.

[.lead]
Skip Paul - Manager, Solution Architecture

Skip Paul is a Solution Architecture Manager within Red Hat's North East region. Based in Newton, MA, he leads a team of architects, assigned to
Red Hat's top accounts, tasked with coordinating efforts between sales, engineering and support to build and communicate enterprise level
Open Source solutions.

In his role, Skip also manages Red Hat User Groups within the North East and has presented at events such as Linuxworld and Brainshare.
He holds a Bachelors of Science Degree, with a dual concentration in Information Systems and Marketing, from the Carroll School of Management at Boston College
and enjoys Windsurfing, Surfing, Skiing and English Pointers.

[.lead]
Matt St. Onge - Solutions Architect

Matt joined the Red Hat family mid 2015, having previously run Red Hat practices with a few channel partners and having owned a consulting company
that itself was a Red Hat ISV partner. With over 20 years of Linux & UNIX experience, Matt has been deeply involved in the ever-changing world of Linux.
Ansible, OpenStack and hybrid cloud are some of his greatest passions.

Matt's experience and training also go further than just Linux solutions; he also holds numerous virtualization, storage and ITIL certifications
in addition to his Red Hat credentials. When Matt's not architecting Clouds, he can be found kayaking, hiking or horribly slicing golf balls down the fairway...


****
== Document Copyright

This document was created by and for Red Hat, Inc. It is being released under link:https://creativecommons.org/licenses/by/4.0/[Creative Commons License 4.0]. You are free to re-use it in whole or in part.

You must give appropriate credit, provide a link to the license, and indicate if changes were made. You may do so in any reasonable manner, but not in any way that suggests the licensor endorses you or your use.
