:figure-caption!:
:become_url: http://docs.ansible.com/ansible/become.html#new-command-line-options
:dir_url: http://docs.ansible.com/ansible/playbooks_best_practices.html
:yum_url: http://docs.ansible.com/ansible/yum_module.html
:service_url: http://docs.ansible.com/ansible/service_module.html
:yaml_url: http://docs.ansible.com/ansible/YAMLSyntax.html
:var_url: http://docs.ansible.com/ansible/playbooks_variables.html
:loop_url: http://docs.ansible.com/ansible/playbooks_loops.html
:cond_url: http://docs.ansible.com/ansible/playbooks_conditionals.html


= Lession 2.0 - Adding Flexibility to your Playbooks

---

== Exercise 2.1 - Using Variables, Loops, and Conditionals

---

****
In Lesson 1.0, you were introduced to Ansible Core and Ansible Tower learning the basics.  In Lesson 2.0, we are going
to teach some more advanced ansible skills that will add flexibility and power to your playbooks.

Ansible exists to make tasks simple and repeatable.  We also know that not all systems are exactly alike and often require
some slight change to the way an Ansible playbook is run.  Enter variables, loops, and conditionals.

Variables are how we deal with differences between your systems, allowing you to account for a change in port, IP address
or directory.

Loops enable us to repeat the same task over and over again.  For example, lets say you want to install 10 packages.
By using an ansible loop, you can do that in a single task.

Conditionals are the way in which we make decisions on the fly.  For example, if some of our machines are RHEL 6, we may
want to enable iptables, but if they are RHEL 7, we want to enable firewalld.  Using a conditional allows us to do this
in a single task.

For a full understanding of variables, loops, and conditionals; check out our Ansible documentation on these subjects. +
link:{var_url}[Ansible Variables] +
link:{loop_url}[Ansible Loops] +
link:{cond_url}[Ansible Conditionals]

[.lead]
Section 1 - Adding variables and a loop to your playbook

To begin, we are going to use the playbook you created in Exercise 1.2

====
*Step 1:* Navigate to and open your existing *install_apache.yml* playbook in your editor
----
% cd ~/apache_basic
% vi install_apache.yml
----
*Step 2:* Add some variables to your playbook, after the *become* statement.  These are the addtional packages your playbook
will install on your web servers

[source,bash]
----
  vars:
    http_packages:
      - httpd
      - mod_wsgi
      - libselinux-python
      - firewalld
----


*Step 3:* Modify the *install apache* task to be called *install packages*
[source,bash]
----
tasks:
 - name: install pacakges
   yum:
     name: {{ item }}
     state: present
   with_items: "{{ http_packages }}"

----
====

[NOTE]
*What the Helsinki is happening here!?* +

- `vars:` You've told Ansible the next thing it sees will be a variable name +
- `http_packages` You are defining a list-type variable called http_packages.  What follows
is a list of those packages +
- `{{ item }}` You are telling Ansible that this will expand into a list item like `httpd`, `mod_wsgi`, etc. +
- `with_items: "{{ http_packages }}` This is your loop which is instructing Ansible to perform this task on
every `item` in `http_packages`

[.lead]
Section 2 - Using a Conditional

So, what if I want this playbook to work on RHEL 6 and RHEL 7?  The modules to restart 
====
[source,bash]
----
---
- hosts: web
  name: Install the apache web service
  become: yes
----

====

- ```---``` Defines the beginning of YAML
- ```hosts: web``` Defines the host group in your inventory on which this play will run against
- ```name: Install the apache web service``` This describes our play
- ```become: yes``` Enables user privilege escalation.  The default is sudo, but su, pbrun, and link:{become_url}[several others] are also supported.

[.lead]
Section 3: Adding Tasks to Your Play

Now that we've defined your play, let's add some tasks to get some things done.  Align (vertically) the *t* in ```task``` with the *b* ```become```.  +
Yes, it does actually matter.  In fact, you should make sure all of your playbook statements are aligned in the way shown here. +
If you want to see the entire playbook for reference, skip to the bottom of this exercise.

====
[source,bash]
----
tasks:
 - name: install apache
   yum:
     name: httpd
     state: present

 - name: start httpd
   service:
     name: httpd
     state: started
----

====

- ```tasks:``` This denotes that one or more tasks are about to be defined
- ```- name:``` Each task requires a name which will print to standard output when you run your playbook.
Therefore, give your tasks a name that is short, sweet, and to the point

---

[source,text]
----
yum:
  name: httpd
  state: present
----
- These three lines are calling the Ansible module *yum* to install httpd.
link:{yum_url}[Click here] to see all options for the yum module.

---

[source,text]
----
service:
  name: httpd
  state: started
----
- The next few lines are using the ansible module *service* to start the httpd service.  The service module
is the preferred way of controlling services on remote hosts.  link:{service_url}[Click here] to learn more
about the *service* module.

---

[.lead]
Section 4: Saving your Playbook

Now that you've completed writing your playbook, it would be a shame not to keep it.

Use the ```write/quit``` method in ```vi``` or ```vim``` to save your playbook, i.e. ```Esc :wq!```


And that should do it.  You should now have a fully written playbook called ```install_apache.yml```.
You are ready to automate!

[NOTE]
Ansible (well, YAML really) can be a bit particular about formatting especially around indentation/spacing.  When you all get back to the office,
read up on this link:{yaml_url}[YAML Syntax] a bit more and it will save you some headaches later.  In the meantime, your completed playbook should look
like this.  Take note of the spacing and alignment.

[source,bash]
----
---
- hosts: web
  name: Install the apache web service
  become: yes

  tasks:
    - name: install apache
      yum:
        name: httpd
        state: present

    - name: start httpd
      service:
        name: httpd
        state: started
----
