:service_url: http://docs.ansible.com/ansible/service_module.html
:yaml_url: http://docs.ansible.com/ansible/YAMLSyntax.html
:var_url: http://docs.ansible.com/ansible/playbooks_variables.html
:loop_url: http://docs.ansible.com/ansible/playbooks_loops.html
:cond_url: http://docs.ansible.com/ansible/playbooks_conditionals.html


= Lession 2.0 - Adding Flexibility to your Playbooks

---

== Exercise 2.1 - Using Variables, Loops, and Conditionals

---

****
In Lesson 1.0, you were introduced to Ansible Core and Ansible Tower learning the basics.  In Lesson 2.0, we are going
to teach some more advanced ansible skills that will add flexibility and power to your playbooks.

Ansible exists to make tasks simple and repeatable.  We also know that not all systems are exactly alike and often require
some slight change to the way an Ansible playbook is run.  Enter variables, loops, and conditionals.

Variables are how we deal with differences between your systems, allowing you to account for a change in port, IP address
or directory.

Loops enable us to repeat the same task over and over again.  For example, lets say you want to install 10 packages.
By using an ansible loop, you can do that in a single task.

Conditionals are the way in which we make decisions on the fly.  For example, if we want to ensure a task only runs on
a RHEL server, we can do that with a conditional statement.

For a full understanding of variables, loops, and conditionals; check out our Ansible documentation on these subjects. +
link:{var_url}[Ansible Variables] +
link:{loop_url}[Ansible Loops] +
link:{cond_url}[Ansible Conditionals]

[.lead]
Section 1 - Adding variables and a loop to your playbook

To begin, we are going to use the playbook you created in Exercise 1.2

====
*Step 1:* Navigate to and open your existing *install_apache.yml* playbook in your editor
----
% cd ~/apache_basic
% vi install_apache.yml
----
*Step 2:* Add some variables to your playbook, after the *become* statement.  These are the addtional packages your playbook
will install on your web servers

[source,bash]
----
  vars:
    http_packages:
      - httpd
      - mod_wsgi
      - libselinux-python
----


*Step 3:* Modify the *install apache* task to be called *install packages*
[source,bash]
----
tasks:
 - name: install packages
   yum:
     name: {{ item }}
     state: present
   with_items: "{{ http_packages }}"


----
====

[NOTE]
====
*What the Helsinki is happening here!?* +

- `vars:` You've told Ansible the next thing it sees will be a variable name +
- `http_packages` You are defining a list-type variable called http_packages.  What follows
is a list of those packages +
- `{{ item }}` You are telling Ansible that this will expand into a list item like `httpd`, `mod_wsgi`, etc. +
- `with_items: "{{ http_packages }}` This is your loop which is instructing Ansible to perform this task on
every `item` in `http_packages`
====

[.lead]
Section 2 - Using a Conditional

So, what if I want this playbook to only work on a Red Hat Enterprise Linux server?  It's pretty simple actually.
Just add a conditional statement under the `with_items:` statement like so.

====
[subs=+quotes]
----
tasks:
 - name: install packages
   yum:
     name: {{ item }}
     state: present
   with_items: "{{ http_packages }}"
   *when: ansible_os_family  == 'RedHat'*
----
====

[NOTE]
====
*What the What!?* +

  - `when:` This instructs Ansible to only run the previous task *when* a condition is met +
- `ansible_os_family == 'RedHat'` `ansible_os_family` is an ansible fact that was gathered as soon as the playbook
started.  Remember, exercise 1.1, Step 3?  The `setup` module collects a bunch of ansible facts that can be referenced
throughout the play.  It will run at the start of every playbook unless you tell it not to. +
====

[.lead]
Section 3: Review

[IMPORTANT]
====
How are we doing so far?  +
We will continue adding to this playbook in the next exercise, but let's just review to make sure
everything looks right.  You're playbook should like the following at this point.
====

[source,bash]
----
---
- hosts: web
  name: Install the apache web service
  become: yes

  vars:
    http_packages:
      - httpd
      - mod_wsgi
      - libselinux-python

  tasks:
   - name: install packages
     yum:
       name: {{ item }}
       state: present
     with_items: "{{ http_packages }}"
     when: ansible_os_family  == 'RedHat'
----
